export const TROPHYFISHES = [
    {
        name: "Sulphur Skitter",
        description: "Caught near Sulphur blocks.",
        type: "&f",
        bronze: false,
        silver:false,
        gold:false,
        diamond:false,
    },
    {
        name: "Obfuscated 1",
        description: "Caught with Corrupted Bait.",
        type: "&f",
        bronze: false,
        silver: false,
        gold: false,
        diamond: false,
    },
    {
        name: "Steaming-Hot Flounder",
        description: "Found in Volcano Geysers.",
        type: "&f",
        bronze: false,
        silver: false,
        gold: false,
        diamond: false,
    },
    {
        name: "Gusher",
        description: "Caught after a volcano eruption.",
        type: "&f",
        bronze: false,
        silver: false,
        gold: false,
        diamond: false,
    },
    {
        name: "Blobfish",
        description: "Caught everywhere.",
        type: "&f",
        bronze: false,
        silver: false,
        gold: false,
        diamond: false,
    },
    {
        name: "Obfuscated 2",
        description: "Caught with Obfuscated 1 Bait.",
        type: "&a",
        bronze: false,
        silver: false,
        gold: false,
        diamond: false,
    },
    {
        name: "Slugfish",
        description: "Bobber must me active for 20 seconds.",
        type: "&a",
        bronze: false,
        silver: false,
        gold: false,
        diamond: false,
    },
    {
        name: "Flyfish",
        description: "Caught from 8 blocks above.\nFound in blazing Volcano",
        type: "&a",
        bronze: false,
        silver: false,
        gold: false,
        diamond: false,
    },
    {
        name: "Obfuscated 3",
        description: "Caught with Obfuscated 2 Bait.",
        type: "&9",
        bronze: false,
        silver: false,
        gold: false,
        diamond: false,
    },
    {
        name: "Lavahorse",
        description: "Caught everywhere.",
        type: "&9",
        bronze: false,
        silver: false,
        gold: false,
        diamond: false,
    },
    {
        name: "Mana Ray",
        description: "Lured by having a high amount of mana.\n 1200+ mana",
        type: "&9",
        bronze: false,
        silver: false,
        gold: false,
        diamond: false,
    },
    {
        name: "Volcanic Stonefish",
        description: "Found in Blazing Volcano.",
        type: "&9",
        bronze: false,
        silver: false,
        gold: false,
        diamond: false,
    },
    {
        name: "Vanille",
        description: "Only caught with &aStarter Lava Rod&f with no enchantments.",
        type: "&9",
        bronze: false,
        silver: false,
        gold: false,
        diamond: false,
    },
    {
        name: "Skeleton Fish",
        description: "Found in Burning Desert.",
        type: "&d",
        bronze: false,
        silver: false,
        gold: false,
        diamond: false,
    },
    {
        name: "Moldfin",
        description: "Found in Mystic Marsh.",
        type: "&d",
        bronze: false,
        silver: false,
        gold: false,
        diamond: false,
    },
    {
        name: "Soul Fish",
        description: "Found in Stronghold.",
        type: "&d",
        bronze: false,
        silver: false,
        gold: false,
        diamond: false,
    },
    {
        name: "Karate Fish",
        description: "Found in Dojo.",
        type: "&d",
        bronze: false,
        silver: false,
        gold: false,
        diamond: false,
    },
    {
        name: "Golden Fish",
        description: "Found swimming around the lava.",
        type: "&6",
        bronze: false,
        silver: false,
        gold: false,
        diamond: false,
    },
]